### ISSUE TITLE
Recommendation for dealing with dynamic clients

### ISSUE THREAD

**Issue by zendes** [nanomsg/mangos#112]
Hi,

I'm looking to implement a client using the bus protocol and I've gotten my basic example working. I have my infrastructure deployed to ec2 using an autoscaling group, and I can query that to get the list of IPs in that group. I want to open a connection to all the other machines in this group, but how do I get access to the pipes in the Socket so I can see if a connection to each address already exists?

Alternatively, is there a way to filter out a new Dial request if it is an already established connection? In my current setup where every instance tries to connect to every other instance, I end up with duplicated messages because as far as I can tell the connection "instance-a connects to listener on instance-b" is considered a different connection than "instance-b connects to listener on instance-a", even though both connect instance-a to instance-b.

Am I doing something wrong, and if so can you send me some pointers as to where I should look?

**Comment by gdamore** [comment]
We don’t already have that, but what you can do is look at the pipe list by watching for connection events.

This is a common enough problem that I think it would be a great idea to build a new “protocol” for a fully connected mesh – which would basically allow one to establish a set of peers, and discard connections from already connected peers.  Perhaps using a generated peer ID.

(If someone wants to sponsor that work, send a message to info@staysail.tech)

Sent from Mail for Windows 10

From: Dennis Marinus
Sent: Tuesday, August 13, 2019 4:41 PM
To: nanomsg/mangos
Cc: Subscribed
Subject: [nanomsg/mangos] Reccoemdation for dealing with dynamic clients(#112)

Hi,
I'm looking to implement a client using the bus protocol and I've gotten my basic example working. I have my infrastructure deployed to ec2 using an autoscaling group, and I can query that to get the list of IPs in that group. I want to open a connection to all the other machines in this group, but how do I get access to the pipes in the Socket so I can see if a connection to each address already exists?
Alternatively, is there a way to filter out a new Dial request if it is an already established connection? In my current setup where every instance tries to connect to every other instance, I end up with duplicated messages because as far as I can tell the connection "instance-a connects to listener on instance-b" is considered a different connection than "instance-b connects to listener on instance-a", even though both connect instance-a to instance-b.
Am I doing something wrong, and if so can you send me some pointers as to where I should look?

**Comment by zendes** [comment]
Got it. I'll go check internally if we have the time to contribute to this and if I can get legal signoff. I'll get back to you.

**Comment by agerlach** [comment]
Is there any new news on this front? I am facing this exact issue. @gdamore could you elaborate on 

> but what you can do is look at the pipe list by watching for connection events.

Thanks for your time

**Comment by gdamore** [comment]
I've not heard back from the submitter, and haven't had cycles to work on it myself.

Watching for connection events is done with the PipeEventHook on the socket.  See the Socket.SetPipeEventHook() API.

**Comment by gdamore** [comment]
Also, if you're not needing a fully connected mesh, you might want to consider the use of a central device, with everyone connecting to it.

**Comment by agerlach** [comment]
Thanks. I cannot use a centralized device. I am setting up a multi-agent framework for testing distributed consensus algorithms. I need to be able to represent arbitrary undirected graphs.

**Comment by rico256-cn** [comment]
@gdamore  How to use the Socket.SetPipeEventHook() API?  Could you provide an example ？ Thanks.
