### ISSUE TITLE
Request for SO_REUSEADDR option in binding socket.

### ISSUE THREAD

**Issue by ghts** [nanomsg/mangos#197]
Dear mangos team.

I suffer from left open binding TCP socket after test case failure.

In the next test case run, I get 

`bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.`

and test case restart fails.

The only solution is rebooting the entire system, which take quite some development time away.

Google found this link for me, which suggest SO_REUSEADDR option is the answer.

https://stackoverflow.com/questions/5875177/how-to-close-a-socket-left-open-by-a-killed-program

But, mangos does not give me a choice of SO_REUSEADDR.

How about adding SO_REUSEADDR option to mangos??

It will save a lot of develpment time.

Sorry for poor English and thank you for reading.

Best Regards

PS>
Quick search in golang source code tree reveals 
'syscall.SO_REUSEADDR' is defined & used in syscall & net package for a wide variety of h/w and o/s.
So, I guess SO_REUSEADDR should not be a compatibility problem.

In golang net package source code, many OS have 'SO_REUSEADDR' option included in 'net.setDefaultListenerSockopts()' function.
So, if Go team included this option as default, 
it should not be the most dangerouse option to include, I guess. ^^

So, please consider positively for development efficiency shake.

**Comment by gdamore** [comment]
Because it's in the default, it's already set where appropriate.

There are some systems where it is unsafe --- for example the semantic of this option is quite different on Windows.

The other thing is that SO_REUSEADDR doesn't necessarily fix *all* the use cases of an address left in use.  There are situations where a socket in TIME_WAIT can still wind up holding on to the TCP port.

You shouldn't need to reboot for this... you may need to wait a little bit of time though.

**Comment by gdamore** [comment]
Most likely this request is for Windows, and on Windows SO_REUSEADDR has a semantic that is breaking for other uses -- it allows applications to concurrently bind to the same address (it behaves more like SO_REUSEPORT).

Consequently, I'm going to respectfully decline to "address" this issue.

What I generally do in my test code where I'm opening and reusing the same sockets is two fold:

1. Use localaddr (127.0.0.1) addresses -- these generally are immediately available after unbind, as there is no need for them to enter TIME_WAIT state.

2. Use dynamic (random or otherwise) addresses when possible.  This way you wind up not always hitting the same TCP port.

**Comment by ghts** [comment]
Thank you for kind explanation.

Yes, it was a request for Windows and now I got it.

I will try use localaddr.

Thank you for help.
