### ISSUE TITLE
How go get ?

### ISSUE THREAD

**Issue by richrarobi** [nanomsg/mangos#199]
Pardon me for being obtuse....

-With v2, I just entered :-  go get "nanomsg.org/go/mangos/v2" , at the command-line,
I tried :-  go get "go.nanomsg.org/mangos/v3" , to no avail.

After trying various other things I give up. Please give me a clue.

**Comment by gdamore** [comment]
What version of go are you using?  With v3 you should really be using go modules.  If you are using go get (old style) stick with v2 for now.

**Comment by richrarobi** [comment]
Thanks for that, I sometimes forget to keep up with changes, although I keep up with the versions! Will have to read up go modules....

**Comment by gdamore** [comment]
The introduction of go modules broke a lot of things, and was a major hassle.  I believe they are good thing, and ultimately will do much to make everyone's lives better in the long run.  But the transition was lot more painful than I would have liked.

There is unfortunately no easy for mangos to support both legacy go get and modules in the same repo, because of the combination of versioning, using git branches for versioning, and vanity names.  I spent many hours trying to make something work before giving up in frustration.
