### ISSUE TITLE
Pull/Push Question

### ISSUE THREAD

**Issue by gmonk** [nanomsg/mangos#268]
Does the pull/push pair buffer data if one or the other is not available?  I am doing a remote packet capture and then pushing that data to a remote pc running nanocat (for testing) but I noticed if the pull side is not up the push side seems to buffer the data and when I do bring up the pull side via nanocat  it receives several messages at once  when the messages should only appear once per second. How do I prevent this from happening ? Or should I use a different topology

**Comment by gdamore** [comment]
If no peer is available, it does hold (buffer) data until the peer is available.

If you don't like that, set the buffer size to either 1 or 0, and it should just fail.

Note that if you use bus protocol but only connect a single peer, it will behave more like what you expect - it drops messages instead of trying harder to hold for later delivery.

**Comment by gmonk** [comment]
Thank you for the information I will try the bus protocol.   With push/pull would the buffer be considered OptionWriteQLen ?

**Comment by gdamore** [comment]
Yes.
