### ISSUE TITLE
Req does not retry properly on disconnect

### ISSUE THREAD

**Issue by edermi** [nanomsg/mangos#338]
Hi,

I'm currently trying to get the Send() timeout to work with the REQ/REP protocol. This is a little modification of the req/rep example (basically client and server were renamed and splitted into two files so I can test over network):

~~~go
func client(url string) {
	var sock mangos.Socket
	var err error
	var msg []byte

	if sock, err = req.NewSocket(); err != nil {
		die("can't get new req socket: %s", err.Error())
	}
	sock.AddTransport(tcp.NewTransport())
	sock.SetOption(mangos.OptionSendDeadline, 2*time.Second)
        // sock.SetOption(mangos.OptionRecvDeadline, 2*time.Second)
	if err = sock.Dial(url); err != nil {
		die("can't dial on req socket: %s", err.Error())
	}
	fmt.Printf("5 secs to kill the server\n")
	time.Sleep(time.Second * 5)

	if err = sock.Send([]byte("DATA")); err != nil {
		die("can't send message on push socket: %s", err.Error())
	}

	if msg, err = sock.Recv(); err != nil {
		die("can't receive data: %s", err.Error())
	}

	fmt.Printf("CLIENT: RECEIVED DATA \n")
	println(&msg)

	sock.Close()
}
~~~

During the 5 seconds time, I kill the server which I'm connected to, so the Send() call is supposed to timeout and the code should die, but unfortunately it continues running and hangs forever in Recv(), even after a server restart it keeps hanging (which makes sense of course).

The timeout for Recv() works as intended so I suppose this is a bug.

**Comment by gdamore** [comment]
Mangos v1 has a defect here where it can take some time (longer than it should) to recover from a disconnect.  Mangos v2 has that defect fixed.

I’ll take a look at this and see if there is something I can do.

In the meantime, I recommend making sure that you have adjusted the reconnect interval to a small value (see OptionReconnectTime.)

 - Garrett

**Comment by edermi** [comment]
The reconnect option assumes that the server comes back? I want to deal with the case the server dies and stays offline. Since Recv() timeouts work fine I currently I have use them as a workaround to deal with this case, but the cleaner solution would probably be to detect that the Send() actually failed/timed out.

**Comment by gdamore** [comment]
So the problem (bug synopsis is wrong), I'll correct it, as Send() does timeout, but we're talking about something else here.

So mangos v1 had at one point a chance to make it notice a dropped connection and immediately select and choose another one (or put it at the head of the queue for a retransmit.) The code to do that was backed out, as it was found problematic.  Consequently, you have to wait for the configured Retry interval (OptionRetryTime) before the request will be sent out.  You need to tune that value sensibly.  Its still not optimal, because we could immediately retry the REQ if the REP we used has disconnected, but as I said, the change to do that was broken and backed out. 

Mangos v2 does this correctly.  The bug I mentioned above was specific to mangos v2, and I fixed that yesterday.   So while I'm not recommending mangos v2 for production use *yet* (as the API isn't completely stable yet -- there is one more significant API breaking change I want to make -- basically the PortHook API needs to be redone -- but if you're not using that it won't matter to you), you could start your experimentation on that now.

Mangos v2 will probably have its first "official" release (the v2 tag applied) in the coming week or so.  So switching now isn't a bad idea.

You can find mangos v2 at github.com/nanomsg/mangos-v2 -- the import path is "nanomsg.org/go/mangos/v2".

**Comment by gdamore** [comment]
(shorter than RetryTime I mean.)

**Comment by edermi** [comment]
Great, thanks for the fast and detailed explanations and the ETA for mangos v2. I'm working on a new project but wanted to rely on a stable codebase. If you are going to make it official the next weeks I'm going to give it a shot.

**Comment by gdamore** [comment]
This is now fixed in mangos v2, and mangos v2 is now considered generally available (though not tagged yet).  Closing it here.
