### ISSUE TITLE
Godoc: Missing Packages

### ISSUE THREAD

**Issue by seoester** [nanomsg/mangos#91]
The documentation on godoc.org for the custom import url seems to be missing packages (this page is referenced by the badge in README):

 * https://godoc.org/nanomsg.org/go/mangos/v2

Godoc seems to properly detect everything when using the GitHub repo as the import path:

 * https://godoc.org/github.com/nanomsg/mangos

I noticed that the go-get info page at `https://nanomsg.org/go/mangos/v2?go-get=1` still references the old repository url. But I don't know whether that is the cause of the issue (go get generally works fine):

```html
<meta name="go-import" content="nanomsg.org/go/mangos/v2 git https://github.com/nanomsg/mangos-v2">
<meta name="go-source" content="nanomsg.org/go/mangos/v2 https://github.com/nanomsg/mangos-v2 _ https://github.com/nanomsg/mangos-v2/tree/master{/dir} https://github.com/nanomsg/mangos-v2/blob/master{/dir}{file}#L{line}">
```

**Comment by gdamore** [comment]
We got hammered hard with the changes for modules.  I'm going to wait until go 1.13 releases (in another two months) before I make any more changes here -- hopefully then it will be stable.

**Comment by seoester** [comment]
This issue is (probably) caused by the old repo url in go-get info page and not related to modules.
I don't believe the go-get lookup behaviour has been changed in a long time, do you expect any changes in 1.13?

Having broken documentation is rather frustrating for the users of mangos. If you find a minute, please fix this issue to ensure that anybody who wants to use mangos has access to the necessary documentation.

**Comment by gdamore** [comment]
The challenge is that the syntax is not well documented in the face of versioning and modules which have changed the URL. My concern is I dont know what the right URL is. Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Seoester <notifications@github.com> Date: 6/28/19  5:56 AM  (GMT-05:00) To: nanomsg/mangos <mangos@noreply.github.com> Cc: gdamore <garrett@damore.org>, Comment <comment@noreply.github.com> Subject: Re: [nanomsg/mangos] Godoc: Missing Packages (#91) This issue is (probably) caused by the old repo url in go-get info page and not related to modules.
I don't believe the go-get lookup behaviour has been changed in a long time, do you expect any changes in 1.13?
Having broken documentation is rather frustrating for the users of mangos. If you find a minute, please fix this issue to ensure that anybody who wants to use mangos has access to the necessary documentation.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/nanomsg/mangos/issues/91?email_source=notifications\u0026email_token=AAJ4G7KLOBYDDFR7ZP6NPH3P4XN4JA5CNFSM4HKZL3LKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYZURYY#issuecomment-506677475",
"url": "https://github.com/nanomsg/mangos/issues/91?email_source=notifications\u0026email_token=AAJ4G7KLOBYDDFR7ZP6NPH3P4XN4JA5CNFSM4HKZL3LKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYZURYY#issuecomment-506677475",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by seoester** [comment]
I see your concern.

It is my understanding that the godoc.org website (gddo) has not received module support yet (https://github.com/golang/gddo/issues/567). So gddo just reads the master branch (or whatever branch is specified in `go-source`). For this repository, this does not pose a major problem, as the master branch is used for v2 development.
Of course, the optimal behaviour would be that users can view docs for a specific version. But there is no way until gddo receives module support.

The current state is that the tools rely on GitHub's redirect feature for checking out the correct repository.
I feel like we can only improve on this behaviour by changing the `go-source` and `go-import` to the correct repository. No functionality would be broken by the change.

**Comment by seoester** [comment]
This might not fix the problem though: I noticed that the meta files are missing for many of the packages. Without these files, gddo may simply be unable to detect the packages.

E.g.:
 * `https://nanomsg.org/go/mangos/v2/protocol/rep/` exists
 * `https://nanomsg.org/go/mangos/v2/protocol/pull/` does not exist
 * ...

**Comment by gdamore** [comment]
It is even more complicated by the use of vanity names. Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Seoester <notifications@github.com> Date: 6/30/19  11:21 AM  (GMT-08:00) To: nanomsg/mangos <mangos@noreply.github.com> Cc: gdamore <garrett@damore.org>, Comment <comment@noreply.github.com> Subject: Re: [nanomsg/mangos] Godoc: Missing Packages (#91) I see your concern.
It is my understanding that the godoc.org website (gddo) has not received module support yet (golang/gddo#567). So gddo just reads the master branch (or whatever branch is specified in go-source). For this repository, this does not pose a major problem, as the master branch is used for v2 development.
Of course, the optimal behaviour would be that users can view docs for a specific version. But there is no way until gddo receives module support.
The current state is that the tools rely on GitHub's redirect feature for checking out the correct repository.
I feel like we can only improve on this behaviour by changing the go-source and go-import to the correct repository. No functionality would be broken by the change.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/nanomsg/mangos/issues/91?email_source=notifications\u0026email_token=AAJ4G7JVDKO62CIA2ASYGJLP5D2RFA5CNFSM4HKZL3LKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODY4RC3I#issuecomment-507056493",
"url": "https://github.com/nanomsg/mangos/issues/91?email_source=notifications\u0026email_token=AAJ4G7JVDKO62CIA2ASYGJLP5D2RFA5CNFSM4HKZL3LKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODY4RC3I#issuecomment-507056493",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by seoester** [comment]
"Vanity URLs" use the "remote import path" feature of `go get`. The feature is widely used, even for the golang.org/x/ repositories.

I don't think the changes I suggested are putting the project at any risk, what kind of problems do you see?

**Comment by gdamore** [comment]
Do you have specific changes to suggest?  The reason I bring all this up is that it is a lot of work to test this to make sure it works, and it requires changes to the production server (the vanity server), which I worry raises risks for folks trying to actually *use* the code.

The main reason I've not put anything correct is that nobody has been able to properly articulate to me *precisely* what the content here should be, and I've had nothing but trouble trying to figure it out on my own.

**Comment by seoester** [comment]
Alright, I might be able to help with that. I'll prepare a low-risk pull request in the next days.

Suggested changes:

1. Change the old repo location to the new repo in all URLs.
2. Create / generate meta pages for all packages of mangos/v2.

**Comment by seoester** [comment]
I am closing this issue as https://github.com/nanomsg/nanomsg/pull/1030 has been merged.

The full documentation is now available at the expected URLs!

https://godoc.org/nanomsg.org/go/mangos/v2#pkg-subdirectories
