### ISSUE TITLE
RPC benchmarks over high-latency networks.

### ISSUE THREAD

**Issue by iwasaki-kenta** [nanomsg/mangos#92]
Hello,

I did a quick benchmark against a high-latency network and reported the results here: https://github.com/iwasaki-kenta/mangos-benchmark

I had issues constructing the concurrent case for the benchmarks and wanted to know if what I noticed was right/wrong.

Also, I would like to request if any options should ideally be set to make these benchmarks for realistic. The motivation for this benchmark is to construct peer-to-peer networks amongst untrusted computers, in which latencies are on the order of a few hundred milliseconds.

**Comment by gdamore** [comment]
I looked at your code, and I think you're probably suffering pretty badly from trying to use a single socket for this all, without the benefit of contexts.

You should consider using OpenContext() and creating a bunch of goroutines to get truly scalable processing.

Having said that, there may still be issues I've not tracked down yet; mangos is designed to work well with long lived connections, and I suspect that there are some places where things that should be parallelized during the session connection phase are not adequately done.... resulting in poor results for short lived connections.

**Comment by gdamore** [comment]
High latency networks suffer badly from the RTT implications.  You really do want to use parallel handling to get multiple requests out the door at once. 

I'm also exploring the idea of using KCP to improve performance on high latency networks; having said that, you'll still need parallelism if you want to scale well -- single threaded performance on such networks will always be rather terrible.  (KCP will improve *throughput*, but not necessarily requests/sec.)

**Comment by gdamore** [comment]
Looked again, the concurrent implementation in your test code is totally busted.  REQ/REP is not concurrent (if you think about it you'll understand why it *cannot* be) although the wire protocol does support it -- you have to use multiple contexts if you're going to use a single REQ or REP socket concurrently (in which case it is fine.)

I'm closing this because your current implementation is terribly deficient -- too much so to really draw any conclusions.  If you want help writing a better test case, contact me out of band.
