### ISSUE TITLE
What's the current status of this library?

### ISSUE THREAD

**Issue by adrianog** [nanomsg/mangos#99]
Would you recommend using this, Mangos 1, nanomsg, or 0mq at this stage?

**Comment by gdamore** [comment]
If you are using go then this is the library to use (unless you need interoperability with 0mq)  Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: AdrianoG <notifications@github.com> Date: 7/1/19  7:51 PM  (GMT-08:00) To: nanomsg/mangos <mangos@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [nanomsg/mangos] What's the current status of this library? (#99) Would you recommend using this, Mangos 1, nanomsg, or 0mq at this stage?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/nanomsg/mangos/issues/99?email_source=notifications\u0026email_token=AAJ4G7MVXRFOUM5K4MP44RDP5K7CXA5CNFSM4H4XQCHKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G4YXMWQ",
"url": "https://github.com/nanomsg/mangos/issues/99?email_source=notifications\u0026email_token=AAJ4G7MVXRFOUM5K4MP44RDP5K7CXA5CNFSM4H4XQCHKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G4YXMWQ",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by gdamore** [comment]
So, if you are using Go, use this one.

I'm closing this ticket, because it's just a question.
